### ISSUE TITLE
Not all DigitalInstantiations from Batches#show are shown in Assets details page

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ams#289]
**Background:** After ingest, when looking at `/batches/[id]`, some Assets show that they have child `DigitalInstantiations` which aren't showing up when you go to the details page for the Asset.

**Comment by afred** [comment]
This is happening because for reasons unknown, some of the `PhysicalInstantiation` objects are _not_ getting added as `ordered` members of the `Asset` instance.

The result of this is that the `DigitalInstantiation` is missing from the display, because only the `ordered_members` are shown.

It's unclear why one `DigitalInstantiation` might be not getting added as an ordered members, while others are; the code to add the `DigitalInstantiation` to the `Asset` is the same (in the ingest gem and in the actor stack).

Current hypothesis:
1. We are establishing the relationship between `DigitalInstantiation` and `Asset` by setting the `in_work_ids` param of the child `DigitalInstantiation` (as are we for parent-child relationships between other model types).
1. There may be something in the metadata of the objects

**Comment by sroosa** [comment]
@afred why did you reopen this? Is there additional work that needs to be done?

**Comment by sroosa** [comment]
Email is sent. Testing on a production instance.
