### ISSUE TITLE
Missing locale terms resulting in ugly HTML showing up in modal to Add User to Group

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ams#390]
**Describe the bug**
When you go to add a user to a group... this is what you get in the modal...
![image](https://user-images.githubusercontent.com/1507490/68615393-f9bdf900-0490-11ea-9c33-eefe79afafaa.png

**To Reproduce**
1. Login as an admin user and go to the 'Manage Roles' link in the dashboard.
2. Click on any group
3. Click on 'Add User +' button
4. behold the ugly html

**Expected behavior**
Don't show that ugliness.

**Done when**
- [x] Add the missing locale term
- [x] verify ugly html doesn't show up
- [ ] (optional) don't display the ugly html even when the locale term is missing.

**Comment by sroosa** [comment]
Closed by #395
