### ISSUE TITLE
AMS should not need to know exactly where bundler is on AAPB host

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/ams#422]
### Problem

When we're pushing records from AMS to AAPB, we run some commands over SSH.

Specifically, we run `bundle exec...` inside of `app/services/ams/export/export_service.rb`.

Apparently there were some problems with being able to find `bundler` on the AAPB host, presumably because we RVM magic wasn't kicking in (in order to find the gem path), and the RVM magic wasn't kicking in presumably because we weren't loading the environment as if it were a login shell.

I ran a manual test using `bash -l` and this allowed `bundle exec` to execute successfully on the remote AAPB host.

If we don't fix this, then one possibility, is that the AAPB host increments `bundler` gem to a latest point release, and it breaks AMS push-to-aapb code... which would probably come as a mystery, and probably take a while to figure out.

### Done when
We try the following code in `app/services/ams/export/export_service.rb`...
```
# This command does the following...
# 1. SSH's into the AAPB host, using a private SSH key on this host.
# 2. Executes `bash -l` on the AAPB host, which simulate a login so that RVM will work properly, and
#    automatically set the gem path, where the currently installed version of bundler lives.
# 3. Executes the `download_clean_ingest.rb` script in the context of a login bash shell.
output << `ssh #{aapb_key_path} ec2-user@#{aapb_host} 'bash -l -c "cd /var/www/aapb/current && RAILS_ENV=production bundle exec /usr/bin/ruby scripts/download_clean_ingest.rb --files /home/ec2-user/ingest_zips/*.xml"'`
```

**Comment by foglabs-zen** [comment]
Drew did it
