### ISSUE TITLE
Add Unit Tests for AMS2-AAPB push/ExportService

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/ams#436]
Because the push functionality is intended to be the main method of moving data from AMS2 to AAPB, we want to add some unit tests to AMS to verify that we are exporting PBCore with everything the AAPBody needs:

-verify that instantiationAnnotation type="organization" is properly cased (to hook into contributing_organizations[] solr field)
-complete contribution -> pbcoreCreator, etc. mapping
-etc

** Done When **
Closed in favor of https://app.zenhub.com/workspaces/mla-developers-5d0a8ef27c5752598acebdb1/issues/wgbh-mla/ams/497 and https://app.zenhub.com/workspaces/mla-developers-5d0a8ef27c5752598acebdb1/issues/wgbh-mla/ams/496

**Comment by singlesoliloquy** [comment]
@foglabs @afred has this been done?

**Comment by afred** [comment]
@singlesoliloquy Not yet. Unit tests would be specific to the Export machinery, which I'm refactoring, but it's slow going with all the priority side-tracks. Additional unit tests can be added to the `Pushes` model as well.

**Comment by singlesoliloquy** [comment]
Ready for acceptance testing when a working stack is up. Part of Drew's refactor.
