### ISSUE TITLE
How do we take care of all the records that failed ingest?

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/ams#443]
Question: How do we take care of all the records that failed ingest?

**Comment by jasoncorum** [comment]
On AMS I'm spot-checking GUIDs from this failed ingest (http://ams-edge.wgbh-mla.org/batches/635?locale=en) and seeing that ActiveFedora::Base.find is returning a tombstone for each ID I'm checking. 

The AsetDestroyer which, in turn, is using the ActorStack to destroy Assets doesn't seem to be wiping tombstones. Does that need to be included in the AssetDestroyer?
