### ISSUE TITLE
Add Transcript Source Annotation Type

### ISSUE THREAD

**Issue by foglabs-zen** [WGBH-MLA/ams#474]
## Description

Archivists should be able to add collections to AMS2 with pbcoreAnnotation annotationType="Transcript Source"Pop Up Archive pbcoreAnnotation without the ingest failing.

## Done When

Archivists can successfully ingest items into AMS2 with pbcoreAnnotation annotationType="Transcript Source" Pop Up Archiven pbcoreAnnotation.

Per miranda:

`can "transcript source" be added as an annotation type?`

Add it to CV in `annotation_types.yml`

**Comment by singlesoliloquy** [comment]
I'm bumping this up since it's a blocker.
