### ISSUE TITLE
AAPB Wonky Display of More Than One Outside URL

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/ams#523]
**Describe the bug**
When records have more than one Outside URL in the annotation field, instead of listing the two URLs side by side, the AAPB instead stacks two video players on top of one another! 

**To Reproduce**
1. Add more than one Outside URL annotation to a record.
2. Make the record's Level of User Access "Online Reading Room"
3. In the Sony Ci ID field add the ID "249daf2f92d74a468e098c6b6d1fe6cf" (adding it alongside the original Sony Ci that's already in there should do the trick, no need to delete!)
4. Save record and push to the AAPB
5. Check the AAPB record and see the error

**Expected behavior**
Ideally a record with two Outside URLs would just create two Outside URL links on the AAPB record page.

**Screenshots**

Here's how it looks with two Outside URLs
![AM_recordwithOutsideURLs.png](https://images.zenhubusercontent.com/5fd38131b736e215633119d4/e1f66db5-14fc-4515-a42f-a13653d35dce)

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: All browsers (Chrome and Safari)
 - Version: 10:12:6

**Comment by singlesoliloquy** [comment]
Maybe our logic is backwards.
