### ISSUE TITLE
Plain Title/ Plain Description not allowed to batch-update in AMS2

### ISSUE THREAD

**Issue by mivillesvik** [WGBH-MLA/ams#667]
**Describe the bug**
When trying to run a batch-update in AMS2 for plain title (Asset.title) and plain description (Asset.description) the AMS2 just spits it out and gives a header error. These headers work upon ingest, but only upon update do these fail.

**To Reproduce**
1. make a spreadsheet with GUIDs already in AMS2
2. add columns for Asset.title and/or Asset.description
3. attempt to ingest as a batch

**Expected behavior**
Ideally, the AMS2 would allow these headers to be updated!

**Screenshots**
![Screen Shot 2022-07-14 at 2.38.43 PM.png](https://images.zenhubusercontent.com/5fd38131b736e215633119d4/bb804715-dc9a-4604-aed2-608024b94972)

**Comment by ekemeyer** [comment]
Bringing this back into play - need to be able to update multiple no type titles in New Jersey Network!
