### ISSUE TITLE
WIPR records with non-digitized content and level of user access

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ams#879]
# Details 
I have a list of GUIDs linked to WIPR metadata only records that got created at first with a level of user access. I understand now that the AAPB doesn't like when that happens and I need to remove LUA from all of them, but AMS2 won't let me. Is there a way to fix this?
here's the list (but also, if there's a way for me to do it I will gladly tackle this!!!)

(see comment below for list of IDs)

Submitted by: Caroline (again. sorry)
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread: https://wgbh.slack.com/archives/GMFPBR44V/p1715960730157339

**Comment by ekemeyer** [comment]
Error message @afred pulled from logs
```
F, [2024-05-17T16:22:11.814338 #1] FATAL -- : [e791ee725327882fe1caf617bd898563]   
[e791ee725327882fe1caf617bd898563] ActiveRecord::RecordInvalid (Validation failed: Value can't be blank):
[e791ee725327882fe1caf617bd898563]   
[e791ee725327882fe1caf617bd898563] app/transactions/ams/steps/create_aapb_admin_data.rb:104:in `update_annotation'
[e791ee725327882fe1caf617bd898563] app/transactions/ams/steps/create_aapb_admin_data.rb:91:in `block in set_annotations_attributes'
[e791ee725327882fe1caf617bd898563] app/transactions/ams/steps/create_aapb_admin_data.rb:83:in `each'
[e791ee725327882fe1caf617bd898563] app/transactions/ams/steps/create_aapb_admin_data.rb:83:in `set_annotations_attributes'
[e791ee725327882fe1caf617bd898563] app/transactions/ams/steps/create_aapb_admin_data.rb:47:in `save_aapb_admin_data'
[e791ee725327882fe1caf617bd898563] app/transactions/ams/steps/create_aapb_admin_data.rb:18:in `call'
```

**Comment by afred** [comment]
List of IDs
[wipr_ids_to_remove_lua_annotation.txt](https://github.com/WGBH-MLA/ams/files/15392737/wipr_ids_to_remove_lua_annotation.txt)

**Comment by afred** [comment]
Done!

NOTE: Of the 1192 records in the file, only 29 had a `level_of_user_access` annotation.

I removed the annotation from these 29, re-indexed, and appears to be good to go.
