### ISSUE TITLE
List of Digitized, Not Online Items from KCAW

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ams#887]
# Details 
Could I get an excel spreadsheet ID'ing everything from Alaska station KCAW that is digitized but not available online? The station manger requested it. It should be about 40 items I think. Let me know if you have any questions - thanks!

Submitted by: Michelle
CC in communications: 
Priority: Medium (within this month)
URL: https://americanarchive.org/catalog?f%5Bcontributing_organizations%5D%5B%5D=KCAW+%28AK%29&f[access_types][]=digitized
Slack message thread:

**Comment by foo4thought** [comment]
Done; the GUIDs you seek are in the attached file.

Gory details:


mylocal:~ kevin_carter$ start=0;numFound=$(curl -sS 'https://americanarchive.org/api.json?fl=id&rows=1&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.numFound');while [ "$start" -lt "$numFound"  ];do curl -sS 'https://americanarchive.org/api.json?fl=id&rows=10&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.docs[].id'

 | tr '_' '-' >> Desktop/guids_KCAW_online_not_digitized.txt;start=$[$start+10];done

mylocal:~ kevin_carter$ wc -l Desktop/guids_KCAW_online_not_digitized.txt

      40 Desktop/guids_KCAW_online_not_digitized.txt



Kevin Carter
Senior Systems Analyst/Programmer
617-300-5923
________________________________

**Comment by foo4thought** [comment]
1. convert query of catalog controller to query the api controller
2. use curl and jq in BASH to collect the GUIDs in batches until done
3. send email with results
4. type this

Bonus:  since the number of results was small, here they are:
cpb-aacip-190-03qv9snr
cpb-aacip-190-08hdr8mc
cpb-aacip-190-106wwqzq
cpb-aacip-190-12m63zwr
cpb-aacip-190-149p8f85
cpb-aacip-190-15bcc424
cpb-aacip-190-16c2fsj7
cpb-aacip-190-19s1rq6k
cpb-aacip-190-22h70v08
cpb-aacip-190-27mpg6wr
cpb-aacip-190-31qftx7n
cpb-aacip-190-322bvt62
cpb-aacip-190-36tx997m
cpb-aacip-190-386hdvqv
cpb-aacip-190-38jdfrm8
cpb-aacip-190-40xpp0g9
cpb-aacip-190-41zcrp65
cpb-aacip-190-44pk0t66
cpb-aacip-190-48sbchfw
cpb-aacip-190-49t1g5xn
cpb-aacip-190-5269pdxg
cpb-aacip-190-53jwt0h3
cpb-aacip-190-569324jf
cpb-aacip-190-5918986m
cpb-aacip-190-612ngmcx
cpb-aacip-190-676t1nwq
cpb-aacip-190-6986716v
cpb-aacip-190-77fqzdqq
cpb-aacip-190-82x3fpjk
cpb-aacip-190-83xsjc8h
cpb-aacip-190-86b2rm41
cpb-aacip-190-88qbzvd3
cpb-aacip-190-89d51n3x
cpb-aacip-190-92g79nww
cpb-aacip-190-93ttf79w
cpb-aacip-190-95j9kpc1
cpb-aacip-190-95w6mkbw
cpb-aacip-190-98z8wm8f
cpb-aacip-190-01pg4f9t
cpb-aacip-190-47rn8tst

**Comment by foo4thought** [comment]
Hi Kevin,

Awesome, thanks! Is there any easy way to get a list of the titles attached to these GUIDs? The station manager wants to compare the list to the list of items he wants to send for Mellon.

Thanks,
Michelle

From: Kevin Carter ***@***.***>
Date: Tuesday, June 4, 2024 at 7:06 AM
To: WGBH-MLA/ams ***@***.***>, WGBH-MLA/ams ***@***.***>
Cc: Assign ***@***.***>, Michelle Kelley ***@***.***>
Subject: Re: [WGBH-MLA/ams] List of Digitized, Not Online Items from KCAW (Issue #887)
Done; the GUIDs you seek are in the attached file.

Gory details:


mylocal:~ kevin_carter$ start=0;numFound=$(curl -sS 'https://americanarchive.org/api.json?fl=id&rows=1&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.numFound');while [ "$start" -lt "$numFound"  ];do curl -sS 'https://americanarchive.org/api.json?fl=id&rows=10&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.docs[].id'

 | tr '_' '-' >> Desktop/guids_KCAW_online_not_digitized.txt;start=$[$start+10];done

mylocal:~ kevin_carter$ wc -l Desktop/guids_KCAW_online_not_digitized.txt

      40 Desktop/guids_KCAW_online_not_digitized.txt




Kevin Carter

Senior Systems Analyst/Programmer

[GBH Archives]<https://www.wgbh.org/foundation/what-we-do/media-library-and-archives>

________________________________

**Comment by foo4thought** [comment]
Done; see attached.

It was this easy:



mylocal:Desktop kevin_carter$ start=0;numFound=$(curl -sS 'https://americanarchive.org/api.json?fl=id&rows=1&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.numFound');while [ "$start" -lt "$numFound"  ];do curl -sS 'https://americanarchive.org/api.json?fl=xml&rows=1&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.docs[].xml' | xpath -e ***@***.***="http://americanarchiveinventory.org"]/text()|//pbcoreTitle/@*|//pbcoreTitle/text()' 2>/dev/null | tr -s '\n' '\t' | sed 's#\(cpb-aacip\).#\1-#g' | tee -a guid_titles_KCAW.txt;echo >> guid_titles_KCAW.txt;start=$[$start+1];done




Kevin Carter
Senior Systems Analyst/Programmer
617-300-5923
________________________________

**Comment by foo4thought** [comment]
Amazing, thank you!

From: Kevin Carter ***@***.***>
Date: Tuesday, June 4, 2024 at 10:28 AM
To: Michelle Kelley ***@***.***>, WGBH-MLA/ams ***@***.***>, WGBH-MLA/ams ***@***.***>
Cc: Assign ***@***.***>
Subject: Re: [WGBH-MLA/ams] List of Digitized, Not Online Items from KCAW (Issue #887)
Done; see attached.

It was this easy:



mylocal:Desktop kevin_carter$ start=0;numFound=$(curl -sS 'https://americanarchive.org/api.json?fl=id&rows=1&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.numFound');while [ "$start" -lt "$numFound"  ];do curl -sS 'https://americanarchive.org/api.json?fl=xml&rows=1&q=%28contributing_organizations:%22KCAW+%28AK%29%22%20AND%20access_types:digitized%29%20NOT%20%28access_types:online%29&start='$start | jq -r '.response.docs[].xml' | xpath -e ***@***.***="http://americanarchiveinventory.org"]/text()|//pbcoreTitle/@*|//pbcoreTitle/text()' 2>/dev/null | tr -s '\n' '\t' | sed 's#\(cpb-aacip\).#\1-#g' | tee -a guid_titles_KCAW.txt;echo >> guid_titles_KCAW.txt;start=$[$start+1];done





Kevin Carter

Senior Systems Analyst/Programmer

[GBH Archives]<https://www.wgbh.org/foundation/what-we-do/media-library-and-archives>

________________________________
