### ISSUE TITLE
Asset reports from AMS2 not exporting all metadata

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ams#902]
# Details 
I've noticed that when I try to export an asset report with all WIPR records, the description columns are completely empty, even when there are unique descriptions for records. I do want to send a sheet to WIPR with at least the titles, GUIDs, local ids, and descriptions since I've identified over 3k of their previously unknown records, so the asset report would help tremendously. I'm putting the priority for this ticket as medium, but it doesn't really have to be done in August. I just would like to send it to them before this year ends to completely wrap up WIPR.

Submitted by: Caroline, the bug sniffer :(
CC in communications: 
Priority: Medium (within this month)
URL: 
Slack message thread: https://wgbh.slack.com/archives/GMFPBR44V/p1722602738084919

**Comment by afred** [comment]
this requires either adding fields to [csv_export.](https://github.com/WGBH-MLA/ams/blob/develop/config/csv_export.yml), or creating copy of it, and modifying for use as an additional export type.

**Comment by ekemeyer** [comment]
to respond to request I pulled down .json from AMS2 for each asset with WIPR as a holding org, then used python to locate and parse the many description/title sources. mapped those fields to csv that were not being pulled by current csv_export.yml
